language: r
cache:
- packages
- pip
sudo: required
dist: "trusty"
warnings_are_errors: false

addons:
  apt:
    packages:
      - libgsl0-dbg
      - libgsl0-dev
      - libgsl0ldbl
    update: true

install:
  - sudo apt-get remove -y python && apt-get install -y python3  python3-pip curl
  - sudo rm -f /usr/bin/python && ln -s /usr/bin/python3 /usr/bin/python
  - sudo rm -f /usr/bin/pip && ln -s /usr/bin/pip3 /usr/bin/pip

  - sudo echo "export PATH="/usr/bin/python:$PATH"" >> ~/.profile
  - sudo echo "export PYTHONPATH="/usr/bin/python:$PYTHONPATH"" >> ~/.profile

  - sudo apt-get update && apt-get install -y --no-install-recommends apt-utils
  - sudo apt-get install -y --force-yes build-essential wget git locales locales-all > /dev/nul
  - sudo apt-get install libudunits2-dev

  - sudo pip install git+https://git@github.com/weecology/retriever.git
  - sudo retriever ls > /dev/null
  - sudo pip install  psycopg2 pymysql > /dev/null
  - sudo R_RETICULATE_PYTHON="/usr/bin/python" | echo $R_RETICULATE_PYTHON >>  ~/.Renviron
  - sudo rm -rf ~/.retriever

scritp:
  - retriever ls
  - retriever --version

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - R CMD INSTALL .
    - Rscript -e 'pkgdown::build_site()'
    - Rscript -e 'covr::codecov()'
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_PAT
      keep-history: true
      local-dir: docs
      on:
        branch: master
