language: r
cache:
- packages
- pip
sudo: required
dist: "trusty"
warnings_are_errors: false

addons:
  apt:
    packages:
      - libgsl0-dbg
      - libgsl0-dev
      - libgsl0ldbl
      - python3-dev
      - python3
    update: true

before_install:
  - export PATH=$(which python$R_PYTHON_VERSION):$PATH
  - export PYTHON=$(which python$R_PYTHON_VERSION)
  - export PYTHONPATH=$(which python$R_PYTHON_VERSION):$PYTHONPATH
install:
  - sudo apt-get update -qq
  - sudo apt-get install libudunits2-dev

  # install Retriever python library
  - git clone https://github.com/weecology/retriever.git retriever
  - cd retriever
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo $PYTHON get-pip.py
  - rm -rf get-pip.py
  - sudo $PYTHON -m pip install -r requirements.txt
  - sudo $PYTHON -m pip install pytest-cov -U
  - sudo $PYTHON -m pip install pytest-xdist -U
  - sudo $PYTHON -m pip install  . -U
  - cd ..
  - rm -rf retriever/
  - sudo rm -rf ~/.retriever

  # Exports
  - export PYTHON_CONFIG=python${R_PYTHON_VERSION}-config
  - export PKG_LIBS=`$PYTHON_CONFIG --ldflags`
  - export PKG_CPPFLAGS=`$PYTHON_CONFIG --includes`
  - export PKG_CPPFLAGS+=" -D PYTHONLIBFILE=\\\"libpython${R_PYTHON_VERSION}.so\\\""

scritp:
  - retriever ls
  - retriever --version

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - R CMD INSTALL .
    - Rscript -e 'pkgdown::build_site()'
    - Rscript -e 'covr::codecov()'
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_PAT
      keep-history: true
      local-dir: docs
      on:
        branch: master
